#!/bin/bash
# This deploy hook gets executed after dependencies are resolved and the
# build hook has been run but before the application has been started back
# up again.  This script gets executed directly, so it could be python, php,
# ruby, etc.

# Run db:migrate
#pushd ${OPENSHIFT_REPO_DIR} > /dev/null
#bundle exec rake db:migrate RAILS_ENV="production"
#popd > /dev/null

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
bundle exec rake db:create RAILS_ENV="production"
bundle exec rake db:migrate RAILS_ENV="production"
cp ${OPENSHIFT_DATA_DIR}/application.yml config/application.yml
popd > /dev/null
